version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongo-registro
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
    ports:
      - ${DB_PORT}:27017
    volumes:
      - ./data/mongo:/data/db
  backend:
    build: ./backend-fullstack
    container_name: api-registro
    restart: always
    ports:
      - ${APP_PORT}:3000
    volumes:
      - ./backend-fullstack:/app
      - /app/node_modules
  api:
    build: ./backend-data
    container_name: backend-data
    ports:
      - 5000:5000
    volumes:
      - ./backend-data:/app